apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: appdemo
spec:
  replicas: 1 #here is the configuration for the actual agent always running
  selector:
    matchLabels:
      app: appdemo
  template:
    metadata:
      labels:
        app: appdemo
    spec:
      containers:
      - name: appdemo
        image: labacrtest.azurecr.io/demodotnet6
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://*:8080
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
